jessetilro/pixelperfect

pom.xml, src/test/resources/README.md
Updated project configuration. Merging because master has important commits with respect to the project configuration as well.
=> Update Project Configuration.

README.md
Updated README.md to index the Product Vision and Product Planning draft documents, deliverables for Sprint 1.
=> Update README for Vision and Planning drafts.

pom.xml, src/main/java/README.md, src/main/java/pixelperfect/Game.java
Created a basic Game class as a start of our jMonkeyEngine application. Added JME dependencies for importing (blender) models.
=> Basic JME Game setup.

src/main/java/pixelperfect/Game.java, src/test/java/README.md, src/test/java/pixelperfect/GameTest.java
Added a smoke test for the game/launcher class, which should enhance the test coverage.  Also fixed some minor organization and spacing issues.
=> Game smoke test

README.md
Updated the README.md to provide references to the Scrum Sprint 1 deliverables (Sprint Backlog 2 and Sprint Retrospective 1).
=> Update README with Scrum Sprint 1 deliverables.

pom.xml
Updated the version number for the working version of Sprint 2 to v0.2.0.
=> Update version number to v0.2.0.

README.md
Updated README.md to include references to the Game Design and the Architecture Design documents.
=> Update README deliverables.

README.md
Updated the README to include a section about and reference to the software repository for the client application.
=> Update README client reference.

src/main/java/pixelperfect/Game.java, src/main/java/pixelperfect/event/Event.java, src/main/java/pixelperfect/event/EventListener.java, src/main/java/pixelperfect/event/EventLog.java, src/main/java/pixelperfect/event/EventScheduler.java, src/main/java/pixelperfect/player/CaptainPlayer.java, src/main/java/pixelperfect/player/CrewPlayer.java, src/main/java/pixelperfect/player/Player.java, src/main/java/pixelperfect/spaceship/Route.java, src/main/java/pixelperfect/spaceship/RouteGenerator.java, src/main/java/pixelperfect/spaceship/RouteNode.java, src/main/java/pixelperfect/spaceship/Spaceship.java, src/test/java/pixelperfect/event/EventListenerTest.java, src/test/java/pixelperfect/event/EventLogTest.java, src/test/java/pixelperfect/event/EventSchedulerTest.java, src/test/java/pixelperfect/event/EventTest.java, src/test/java/pixelperfect/player/CaptainPlayerTest.java, src/test/java/pixelperfect/player/CrewPlayerTest.java, src/test/java/pixelperfect/player/PlayerTest.java, src/test/java/pixelperfect/spaceship/RouteGeneratorTest.java, src/test/java/pixelperfect/spaceship/RouteNodeTest.java, src/test/java/pixelperfect/spaceship/RouteTest.java, src/test/java/pixelperfect/spaceship/SpaceshipTest.java
Added a bunch of templates for the classes described in the first version of the UML class diagram designed for Sprint 2. Also introduced templates for corresponding test suites using parallel class hierarchy.
The few tiny features and integrations included are not tested for they will quite likely change a lot during this sprint. In addition some static errors have slipped through, because of the classes being templates rather than full implementations.
The creation of this relatively large bunch of template classes was agreed upon in order to allow cooperation to be done more effectively, for the templates eliminate some coordination overhead.
=> Add Template Classes.

.gitignore, src/main/java/pixelperfect/Game.java, src/main/java/pixelperfect/Spaceship.java, src/main/java/pixelperfect/route/Route.java, src/main/java/pixelperfect/route/RouteGenerator.java, src/main/java/pixelperfect/route/RouteNode.java
I suggest to do this refactoring to routes to make the code more reliable to use.
Also, for now I haven't made Route to be Singleton, because in the future more Route instances might be used for reasons.
=> Refactor singletons packages

src/main/java/pixelperfect/Spaceship.java, src/main/java/pixelperfect/route/Route.java, src/main/java/pixelperfect/route/RouteGenerator.java
Fix some CheckStyle reported errors related to the Route and RouteGenerator classes. Some PMD and FindBugs warnings remain, but these are insignificant and can't be solved right now (unused fields et cetera).
=> Fix Route related  checkstyle

src/main/java/pixelperfect/Game.java, src/main/java/pixelperfect/Spaceship.java, src/main/java/pixelperfect/event/Event.java, src/main/java/pixelperfect/event/EventListener.java, src/main/java/pixelperfect/event/EventLog.java, src/main/java/pixelperfect/event/EventScheduler.java, src/test/java/pixelperfect/event/EventTest.java
Implemented fully functional event scheduling. Events are introduced with a distribution modelled as a poisson process. The queue of active events is monitored, and when an event expires it damages the ship and is discarded from the log. Finally, when the ship's health is depleted, the game is stopped.
Resolves issues #12 and #13.
It is not tested yet, so we have some work to do the upcoming sprint.
=> Implement Event Scheduling

pom.xml
Updated the version number in the POM for the working version of Sprint 3
to v0.3.0.
=> Update version number to v0.3.0.

src/main/java/pixelperfect/Game.java, src/main/java/pixelperfect/event/EventScheduler.java
Updated the EventScheduler update algorithm to an implementation of pseudocode for simulating a
poisson process (reference will be included in the pull-request). Also increased precision, using 64 bit floating point numbers rather than 32 bit. Finally, this implementation allows for multiple events to occur simultaneously (with a really small probability though).
After grabbing my book on probability and statistics I noticed that the EventScheduler wasn't functioning correct yet. Therefore I implemented the first of these algorithms:
[https://en.wikipedia.org/wiki/Poisson_distribution#Generating_Poisson-distributed_random_variables](https://en.wikipedia.org/wiki/Poisson_distribution#Generating_Poisson-distributed_random_variables)
=> Fix EventScheduler Poisson.

src/main/java/pixelperfect/Game.java, src/main/java/pixelperfect/Spaceship.java
The game is completed when the route is completed. For now, every cycle the game will check if the conditions are met.
Issue #51
=> Implemented a very simple Victory condition.

src/main/java/pixelperfect/route/AllyNode.java, src/main/java/pixelperfect/route/AsteroidNode.java, src/main/java/pixelperfect/route/EarthNode.java, src/main/java/pixelperfect/route/EnemyNode.java, src/main/java/pixelperfect/route/MarsNode.java, src/main/java/pixelperfect/route/RouteNode.java, src/test/java/pixelperfect/SpaceshipTest.java, src/test/java/pixelperfect/route/AllyNodeTest.java, src/test/java/pixelperfect/route/AsteroidNodeTest.java, src/test/java/pixelperfect/route/EarthNodeTest.java, src/test/java/pixelperfect/route/EnemyNodeTest.java, src/test/java/pixelperfect/route/MarsNodeTest.java, src/test/java/pixelperfect/route/RouteNodeTest.java
Issue #45 
I have made a simple hierarchy for the RouteNode. This can be refactored later to be an optional decorator for example.
The RouteNode will probably be advanced during the implementation of the RouteGenerator. Also optional functional methods of sub-classes will be updated when working on RouteGenerator and future implementation of Route related classes.
I have also made a simple structure for the testing RouteNode and its sub-classes.
**Note**
Naming conventions when testing:
- methods: test_methodname_() {}
- classes: _classname_Test {}
**Suggestion**
Use '@ Before' to easily initialize objects and use them in the whole test suite.
=> Routenodes expansion

src/main/java/nl/tudelft/pixelperfect/Game.java
Added a few objects to resemble the cockpit
=> Load scene

.gitignore, src/main/java/nl/tudelft/pixelperfect/route/AllyNode.java, src/main/java/nl/tudelft/pixelperfect/route/AsteroidNode.java, src/main/java/nl/tudelft/pixelperfect/route/EarthNode.java, src/main/java/nl/tudelft/pixelperfect/route/EnemyNode.java, src/main/java/nl/tudelft/pixelperfect/route/MarsNode.java, src/main/java/nl/tudelft/pixelperfect/route/Route.java, src/main/java/nl/tudelft/pixelperfect/route/RouteGenerator.java, src/main/java/nl/tudelft/pixelperfect/route/Tuple.java, src/test/java/nl/tudelft/pixelperfect/route/AllyNodeTest.java, src/test/java/nl/tudelft/pixelperfect/route/AsteroidNodeTest.java, src/test/java/nl/tudelft/pixelperfect/route/EarthNodeTest.java, src/test/java/nl/tudelft/pixelperfect/route/EnemyNodeTest.java, src/test/java/nl/tudelft/pixelperfect/route/MarsNodeTest.java, src/test/java/nl/tudelft/pixelperfect/route/RouteNodeTest.java, src/test/java/nl/tudelft/pixelperfect/route/RouteTest.java
Issue #44 
Implemented a simple route generator for now which is semi-hard coded: the route generator knows which RouteNodes exist.
I have also implented an easy Tuple utility class which helps me implement an easy-to-use list of Tuples. This can later be used to make two-way choices.
**Note**: 
- there are still CheckStyle warnings present in other parts of the code.
- no tests are made for this code yet.
=> Routegenerator

src/main/java/nl/tudelft/pixelperfect/Game.java, src/main/java/nl/tudelft/pixelperfect/Spaceship.java, src/main/java/nl/tudelft/pixelperfect/client/ConnectListener.java, src/main/java/nl/tudelft/pixelperfect/client/EventsMessage.java, src/main/java/nl/tudelft/pixelperfect/client/ServerListener.java, src/main/java/nl/tudelft/pixelperfect/event/EventListener.java, src/main/java/nl/tudelft/pixelperfect/event/EventLog.java, src/main/java/nl/tudelft/pixelperfect/player/CaptainPlayer.java, src/main/java/nl/tudelft/pixelperfect/player/CrewPlayer.java, src/main/java/nl/tudelft/pixelperfect/player/Player.java
Issue #67 
Reopened under another branch because it didn't register my merge conflicts.
=> Redone the branch to the changes of the latest merge

src/main/java/nl/tudelft/pixelperfect/Game.java, src/main/java/nl/tudelft/pixelperfect/Scene.java
Give defining the objects its own class. Later on i intend to maybe write some create/factory methods for this to get shorter and cleaner code that can be tested better as well
=> Refactor scene

src/main/java/nl/tudelft/pixelperfect/Scene.java
Using a variable instead of identical literals now
=> Fix for wrong strings in setColor

src/main/java/nl/tudelft/pixelperfect/Game.java, src/main/java/nl/tudelft/pixelperfect/Scene.java, src/main/java/nl/tudelft/pixelperfect/Spaceship.java, src/main/java/nl/tudelft/pixelperfect/client/EventsMessage.java, src/main/java/nl/tudelft/pixelperfect/client/ServerListener.java, src/main/java/nl/tudelft/pixelperfect/event/EventFactory.java, src/main/java/nl/tudelft/pixelperfect/event/EventLog.java, src/test/java/nl/tudelft/pixelperfect/SpaceshipTest.java, src/test/java/nl/tudelft/pixelperfect/event/AsteroidFieldEventTest.java, src/test/java/nl/tudelft/pixelperfect/event/EventFactoryTest.java, src/test/java/nl/tudelft/pixelperfect/event/EventLogTest.java, src/test/java/nl/tudelft/pixelperfect/event/EventTest.java, src/test/java/nl/tudelft/pixelperfect/event/FireEventTest.java, src/test/java/nl/tudelft/pixelperfect/event/HostileShipEventTest.java, src/test/java/nl/tudelft/pixelperfect/event/PlasmaLeakEventTest.java, src/test/java/nl/tudelft/pixelperfect/route/RouteNodeTest.java
Resolved all Checkstyle warnings in the project.
=> Fix checkstyle warnings

src/main/java/nl/tudelft/pixelperfect/player/Player.java, src/test/java/nl/tudelft/pixelperfect/player/CaptainPlayerTest.java, src/test/java/nl/tudelft/pixelperfect/player/CrewPlayerTest.java, src/test/java/nl/tudelft/pixelperfect/player/PlayerTest.java
Updated the Player test suites to conform to a parallel class hierarchy. Updated test cases to increase test coverage.
=> Update Player test suites.

src/main/java/nl/tudelft/pixelperfect/Game.java, src/main/java/nl/tudelft/pixelperfect/Scene.java, src/main/java/nl/tudelft/pixelperfect/Spaceship.java, src/main/java/nl/tudelft/pixelperfect/client/ConnectListener.java, src/main/java/nl/tudelft/pixelperfect/client/EventsMessage.java, src/main/java/nl/tudelft/pixelperfect/client/HelloMessage.java, src/main/java/nl/tudelft/pixelperfect/client/ServerListener.java, src/main/java/nl/tudelft/pixelperfect/event/AsteroidFieldEvent.java, src/main/java/nl/tudelft/pixelperfect/event/Event.java, src/main/java/nl/tudelft/pixelperfect/event/EventFactory.java, src/main/java/nl/tudelft/pixelperfect/event/FireEvent.java, src/main/java/nl/tudelft/pixelperfect/event/HostileShipEvent.java, src/main/java/nl/tudelft/pixelperfect/event/PlasmaLeakEvent.java, src/main/java/nl/tudelft/pixelperfect/player/CaptainPlayer.java, src/main/java/nl/tudelft/pixelperfect/player/CrewPlayer.java, src/main/java/nl/tudelft/pixelperfect/player/Player.java, src/main/java/nl/tudelft/pixelperfect/route/AllyNode.java, src/main/java/nl/tudelft/pixelperfect/route/AsteroidNode.java, src/main/java/nl/tudelft/pixelperfect/route/EarthNode.java, src/main/java/nl/tudelft/pixelperfect/route/EnemyNode.java, src/main/java/nl/tudelft/pixelperfect/route/MarsNode.java, src/main/java/nl/tudelft/pixelperfect/route/Route.java, src/main/java/nl/tudelft/pixelperfect/route/RouteGenerator.java, src/main/java/nl/tudelft/pixelperfect/route/Tuple.java
Cleaned up the javadoc comments a bit.
=> Clean javadoc comments.

src/main/java/nl/tudelft/pixelperfect/Game.java, src/main/java/nl/tudelft/pixelperfect/event/EventLog.java
The networking was defect, since a certain message class was not
serializable.
=> Fix major networking bug.

src/main/java/nl/tudelft/pixelperfect/Game.java, src/main/java/nl/tudelft/pixelperfect/event/EventFactory.java, src/main/java/nl/tudelft/pixelperfect/event/EventListener.java, src/main/java/nl/tudelft/pixelperfect/event/EventLog.java, src/main/java/nl/tudelft/pixelperfect/player/CaptainPlayer.java, src/main/java/nl/tudelft/pixelperfect/player/CrewPlayer.java, src/main/java/nl/tudelft/pixelperfect/player/Player.java, src/main/java/nl/tudelft/pixelperfect/route/RouteGenerator.java, src/test/java/nl/tudelft/pixelperfect/SpaceshipTest.java, src/test/java/nl/tudelft/pixelperfect/event/AsteroidFieldEventTest.java, src/test/java/nl/tudelft/pixelperfect/event/EventTest.java, src/test/java/nl/tudelft/pixelperfect/event/FireEventTest.java, src/test/java/nl/tudelft/pixelperfect/event/HostileShipEventTest.java, src/test/java/nl/tudelft/pixelperfect/event/PlasmaLeakEventTest.java, src/test/java/nl/tudelft/pixelperfect/player/CaptainPlayerTest.java, src/test/java/nl/tudelft/pixelperfect/player/CrewPlayerTest.java, src/test/java/nl/tudelft/pixelperfect/player/PlayerTest.java
Every single CheckStyle, PMD and findBugs warning resolved.
Before release tommorow, please immediately fix all warnings before making a PR.
=> Fix pmd findbugs checkstyle warnings

README.md
Updated the README to contain references to the Sprint 3 deliverable documents.
=> Update README Sprint 3 Documents.

src/main/java/nl/tudelft/pixelperfect/route/RouteNode.java, src/test/java/nl/tudelft/pixelperfect/route/AllyNodeTest.java, src/test/java/nl/tudelft/pixelperfect/route/AsteroidNodeTest.java, src/test/java/nl/tudelft/pixelperfect/route/EarthNodeTest.java, src/test/java/nl/tudelft/pixelperfect/route/EnemyNodeTest.java, src/test/java/nl/tudelft/pixelperfect/route/MarsNodeTest.java, src/test/java/nl/tudelft/pixelperfect/route/RouteNodeTest.java
The RouteNode class should be abstract, since we should work with its
subtypes. Updated the test suite hierarchy to be parallel, using the
factory method design pattern.
=> Update RouteNode to be abstract.

src/main/java/nl/tudelft/pixelperfect/event/EventFactory.java
The defect causing runtime failures is fixed.
Follow up of PR #116.
Related to issues #123 and #113.
=> Refactor Event Factory

src/main/java/nl/tudelft/pixelperfect/event/EventFactory.java, src/main/java/nl/tudelft/pixelperfect/event/EventLog.java, src/test/java/nl/tudelft/pixelperfect/SpaceshipTest.java, src/test/java/nl/tudelft/pixelperfect/client/EventsMessageTest.java, src/test/java/nl/tudelft/pixelperfect/client/ServerListenerTest.java, src/test/java/nl/tudelft/pixelperfect/event/EventFactoryTest.java, src/test/java/nl/tudelft/pixelperfect/event/EventLogTest.java
The new test case checks if the server.broadcast() method is called
exactly once.
=> Updated the test case

src/main/java/nl/tudelft/pixelperfect/Constants.java, src/main/java/nl/tudelft/pixelperfect/gui/GameHeadsUpDisplay.java
Fixed the variable names and their associated references for the Constants class.
=> Fix Constants Style

README.md
Updated the README.md file to contain references to the deliverable documents of sprint 4.
=> Update README docs sprint 4.

pom.xml
Updated the version number in the POM to v0.5.0.
=> Update version number to v0.5.0.

src/main/java/nl/tudelft/pixelperfect/player/Engineer.java, src/main/java/nl/tudelft/pixelperfect/player/Gunner.java, src/main/java/nl/tudelft/pixelperfect/player/Scientist.java, src/test/java/nl/tudelft/pixelperfect/player/CrewPlayerTest.java, src/test/java/nl/tudelft/pixelperfect/player/EngineerTest.java, src/test/java/nl/tudelft/pixelperfect/player/GunnerTest.java, src/test/java/nl/tudelft/pixelperfect/player/ScientistTest.java
Added roles classes to the game code.
Players should be able to select a role at the start of the game.
Added tests accordingly + fixed static warnings.
=> Role classes

src/main/java/nl/tudelft/pixelperfect/Game.java, src/main/java/nl/tudelft/pixelperfect/Scene.java
suggestions from the TA about the imput manager and removed repeated code from the scene.
=> Refactor scene game

src/main/java/nl/tudelft/pixelperfect/Constants.java, src/main/java/nl/tudelft/pixelperfect/gui/GameHeadsUpDisplay.java
Added a simple indicator for the health for the demo, as well as fixing positioning for VR.
=> Gui health score

.scope.yml
Added a configuration file for the SIG analysis tool Better Code Hub. The
.scope.yml declares the component depth and languages.
=> Add SIG config file.

README.md
Updated the README.md file to feature a Coveralls badge.
=> Update README Coveralls Badge.

src/main/java/nl/tudelft/pixelperfect/Constants.java, src/main/java/nl/tudelft/pixelperfect/Game.java, src/main/java/nl/tudelft/pixelperfect/Spaceship.java, src/main/java/nl/tudelft/pixelperfect/event/EventListener.java, src/main/java/nl/tudelft/pixelperfect/event/EventLog.java, src/main/java/nl/tudelft/pixelperfect/gui/GameHeadsUpDisplay.java, src/test/java/nl/tudelft/pixelperfect/SpaceshipTest.java
Added the desired indicators to the HUD, and refactored the HUD class.
=> HUD indicators

src/main/java/nl/tudelft/pixelperfect/client/ServerListener.java, src/main/java/nl/tudelft/pixelperfect/event/EventReader.java, src/main/java/nl/tudelft/pixelperfect/gamestates/PlayState.java, src/main/java/nl/tudelft/pixelperfect/route/RouteGenerator.java, src/test/java/nl/tudelft/pixelperfect/client/ServerListenerTest.java, src/test/java/nl/tudelft/pixelperfect/event/EventTest.java, src/test/java/nl/tudelft/pixelperfect/gamestates/PlayStateTest.java
There are two missing branches in the RouteGenerator and PlayState class
which aren't covered yet.
The reason why is because the RouteGenerator uses a random generator in
the middle of the method that is difficult to mock, while PlayState uses
the VRApplication, which causes a nullpointerException if I try to use
it.
Overall, the branch coverage is now around 79.8%
=> Added more tests to increase coverage

src/main/java/nl/tudelft/pixelperfect/Roles.java
Added the role of Janitor to Roles.
Related PR in client: https://github.com/jessetilro/pixelperfect-client/pull/19
=> Adde the role of Janitor to the Roles Enum class.

src/main/java/nl/tudelft/pixelperfect/Game.java, src/main/java/nl/tudelft/pixelperfect/audio/AudioPlayer.java, src/test/java/nl/tudelft/pixelperfect/audio/AudioPlayerTest.java
AudioPlayer class to store and play/stop sounds. If you think aditional functionality is needed let me know.
=> AudioPlayer

src/main/java/nl/tudelft/pixelperfect/Constants.java, src/main/java/nl/tudelft/pixelperfect/Game.java, src/main/java/nl/tudelft/pixelperfect/Scene.java, src/main/java/nl/tudelft/pixelperfect/Spaceship.java, src/main/java/nl/tudelft/pixelperfect/client/RoleChosenMessage.java, src/main/java/nl/tudelft/pixelperfect/event/EventFactory.java, src/main/java/nl/tudelft/pixelperfect/event/EventListener.java, src/main/java/nl/tudelft/pixelperfect/event/EventReader.java, src/main/java/nl/tudelft/pixelperfect/gamestates/PlayState.java, src/main/java/nl/tudelft/pixelperfect/gamestates/WonState.java, src/main/java/nl/tudelft/pixelperfect/gui/DebugHeadsUpDisplay.java, src/test/java/nl/tudelft/pixelperfect/gamestates/PlayStateTest.java
Changed the current GUI to be a special "debug" mode.  This mode can now be activated by starting the game with P, then clicking the 0 key.  It can be enabled/disabled using the same key.  Meant for debug purposes, and to not impose on the game status/existance.
Also fixed some naming and organization to ensure that the actual heads up display will be named just so.  The development for this will come soon.
=> Gui debug mode

src/main/java/nl/tudelft/pixelperfect/event/Event.java, src/main/java/nl/tudelft/pixelperfect/event/parameter/EventParameterCollection.java, src/main/java/nl/tudelft/pixelperfect/game/Constants.java, src/main/java/nl/tudelft/pixelperfect/game/Game.java, src/main/java/nl/tudelft/pixelperfect/game/Settings.java, src/main/java/nl/tudelft/pixelperfect/gamestates/PlayState.java, src/main/java/nl/tudelft/pixelperfect/gui/DebugHeadsUpDisplay.java, src/test/java/nl/tudelft/pixelperfect/event/EventTest.java, src/test/java/nl/tudelft/pixelperfect/gamestates/PlayStateTest.java
Fixed some static errors and added the parameter values to the debug view.
NB:  The failing builds were due to tests that passed locally and failed on Travis, my apologies.
=> Gui debug parameter

src/main/java/nl/tudelft/pixelperfect/client/ServerListener.java, src/main/java/nl/tudelft/pixelperfect/client/message/EventCompletedMessage.java, src/main/java/nl/tudelft/pixelperfect/event/EventListener.java, src/main/java/nl/tudelft/pixelperfect/event/EventLog.java, src/main/java/nl/tudelft/pixelperfect/event/factory/HostileShipEventFactory.java, src/main/java/nl/tudelft/pixelperfect/event/parameter/EventParameterValues.java, src/main/java/nl/tudelft/pixelperfect/game/Constants.java, src/test/java/nl/tudelft/pixelperfect/client/ServerListenerTest.java, src/test/java/nl/tudelft/pixelperfect/event/EventLogTest.java
EventParameters can now be submitted client-side and validated server-side.
Developed (and should therefore be tested) in parallel with https://github.com/jessetilro/pixelperfect-client/pull/25.
Resolves Issue #220.
=> Event Parameters Networking

src/main/java/nl/tudelft/pixelperfect/event/factory/AsteroidImpactEventFactory.java
For the Server side: added the parameter which can be 0 or 1, Energy Shield or Hyperdrive respectively. 
Related PR client: https://github.com/jessetilro/pixelperfect-client/pull/26
=> Mini game asteroid impact

src/main/java/nl/tudelft/pixelperfect/event/factory/AsteroidImpactEventFactory.java, src/main/resources/data/events.json
Added parameters of Asteroid Impact in the JSON resource file.
=> Added the asteroid parameters of AsteroidImpact.

src/main/java/nl/tudelft/pixelperfect/client/ServerListener.java, src/main/java/nl/tudelft/pixelperfect/event/EventListener.java, src/main/java/nl/tudelft/pixelperfect/event/EventLog.java, src/main/java/nl/tudelft/pixelperfect/game/Game.java, src/main/java/nl/tudelft/pixelperfect/gui/GameHeadsUpDisplay.java, src/test/java/nl/tudelft/pixelperfect/event/EventLogTest.java
Fixed all static errors in the release branch.
=> Fix static errors.

src/main/java/nl/tudelft/pixelperfect/event/EventLog.java, src/test/java/nl/tudelft/pixelperfect/client/ServerListenerTest.java, src/test/java/nl/tudelft/pixelperfect/event/EventLogTest.java, src/test/java/nl/tudelft/pixelperfect/event/EventTest.java, src/test/java/nl/tudelft/pixelperfect/event/parameter/EventParameterCollectionTest.java, src/test/java/nl/tudelft/pixelperfect/gamestates/PlayStateTest.java
Added and edited the tests and fixed some warnings.
Branch coverage should now be around 78.8%
=> Improved test coverage

src/main/java/nl/tudelft/pixelperfect/game/Constants.java, src/main/java/nl/tudelft/pixelperfect/game/Game.java, src/main/java/nl/tudelft/pixelperfect/gui/DebugHeadsUpDisplay.java, src/main/java/nl/tudelft/pixelperfect/gui/GameHeadsUpDisplay.java
-Enhanced the Beta HUD log by showing the parameters and event name.
-Added the ability to see the players connected from within the debug view.
-Added the ability to see the localhost/connection address within the debug view.
=> Gui beta hud parameters

src/main/java/nl/tudelft/pixelperfect/game/Game.java
Fixed a javadoc merge issue that had a merge conflict in it.
=> Fix javadoc issue

src/main/java/nl/tudelft/pixelperfect/event/factory/HostileShipEventFactory.java, src/main/resources/data/events.json
Updated the parameters generated for hostile ship events to be aligned
with the parameters to be entered on the client-side. Updated parameter
description to fit on screen.
Developed (and should therefore be tested) in parallel with PR https://github.com/jessetilro/pixelperfect-client/pull/42
=> Update Hostile Ship Event Parameters.

src/test/java/nl/tudelft/pixelperfect/client/ServerListenerTest.java
=> Updated test to contain new RoleChosen Method

src/main/java/nl/tudelft/pixelperfect/gui/GameHeadsUpDisplay.java, src/test/java/nl/tudelft/pixelperfect/gamestates/StartStateTest.java
I was originally planning to enhanced the GUI with images, but this caused a massive strain on the engine and made the GUI uglier.  I decided against this, and simply removed the temporary event log and refactored the GUI a bit instead.
=> Gui Refactor

src/main/java/nl/tudelft/pixelperfect/event/factory/FireOutbreakEventFactory.java
Added the fire location parameter to the event factory for the fire event.  Must be tested and merged in conjunction with the mobile client PR.
=> Implement Location

src/main/java/nl/tudelft/pixelperfect/event/Event.java, src/main/java/nl/tudelft/pixelperfect/event/type/AsteroidImpactEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/CoffeeBoostEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/FireOutbreakEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/HostileShipEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/PlasmaLeakEvent.java
refactoring some code i wrote last night in a hurry
=> some refactoring to code of last night

src/main/java/nl/tudelft/pixelperfect/event/factory/EventFactory.java, src/main/java/nl/tudelft/pixelperfect/event/parameter/EventParameter.java, src/main/java/nl/tudelft/pixelperfect/event/parameter/EventParameterCollection.java, src/main/java/nl/tudelft/pixelperfect/event/type/AsteroidImpactEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/CoffeeBoostEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/FireOutbreakEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/HostileShipEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/PlasmaLeakEvent.java, src/test/java/nl/tudelft/pixelperfect/event/parameter/EventParameterTest.java
With the changes introduced in PR #310, some defects in the Event
Parameter subsystem were introduced as well. These are fixed by this
commit. Also did some refactoring and optimization.
=> Fix bugs with parameters.

src/main/java/nl/tudelft/pixelperfect/event/factory/FireOutbreakEventFactory.java, src/main/java/nl/tudelft/pixelperfect/event/type/AsteroidImpactEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/CoffeeBoostEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/FireOutbreakEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/HostileShipEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/PlasmaLeakEvent.java, src/main/resources/data/events.json
-Updated the parameters of the fire event to reflect the new, second parameter.
-Updated the scene display of the fire event to include this parameter on the display.
Please only merge this branch once approved and in conjunction with the PR for the client.
ONLY MERGE IN CONJUNCTION WITH CLIENT PR 51.
=> Event fire second parameter

src/main/java/nl/tudelft/pixelperfect/event/type/CoffeeBoostEvent.java, src/main/java/nl/tudelft/pixelperfect/event/type/FireOutbreakEvent.java
somewhere these two sounds must have been removed by accident
=> missing sounds

src/main/java/nl/tudelft/pixelperfect/game/Constants.java, src/main/java/nl/tudelft/pixelperfect/gui/MainMenuDisplay.java
-Fixed the main menu from displaying out of the VR bounds.
-Changed the text to reflect the product.
=> Gui fix startmenu

src/main/java/nl/tudelft/pixelperfect/game/Constants.java, src/test/java/nl/tudelft/pixelperfect/client/ConnectListenerTest.java, src/test/java/nl/tudelft/pixelperfect/player/PlayerCollectionTest.java
=> Fix static errors

pom.xml
Updated the version number of the project to v1.1.0, for the first patch
for next week. This will be the version used for the context assessment,
and possibly also for the presentation and demo market.
=> Update version number.

src/main/java/nl/tudelft/pixelperfect/game/Game.java
disable cursor to release, try 2
=> disable cursor
